apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-89db8
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-jxthh:m-12348520c6d2","addresses":["192.168.2.81"],"port":8083,"protocol":"TCP","podName":"armstronghab:influxdb-5c9d69d59b-7bx5v","allNodes":false},{"nodeName":"c-jxthh:m-12348520c6d2","addresses":["192.168.2.81"],"port":8086,"protocol":"TCP","podName":"armstronghab:influxdb-5c9d69d59b-7bx5v","allNodes":false},{"nodeName":"c-jxthh:m-12348520c6d2","addresses":["192.168.2.81"],"port":8090,"protocol":"TCP","podName":"armstronghab:influxdb-5c9d69d59b-7bx5v","allNodes":false},{"nodeName":"c-jxthh:m-12348520c6d2","addresses":["192.168.2.81"],"port":25826,"protocol":"UDP","podName":"armstronghab:influxdb-5c9d69d59b-7bx5v","allNodes":false},{"nodeName":"c-jxthh:m-12348520c6d2","addresses":["192.168.2.81"],"port":2003,"protocol":"TCP","podName":"armstronghab:influxdb-5c9d69d59b-7bx5v","allNodes":false}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-armstronghab-influxdb
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/publicEndpoints: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:cattle.io/timestamp: {}
              f:field.cattle.io/ports: {}
              f:field.cattle.io/publicEndpoints: {}
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:containers:
              k:{"name":"influxdb"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"INFLUXDB_ADMIN_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_ADMIN_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_DATA_ENGINE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_DB"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_READ_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_READ_USER_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_REPORTING_DISABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"INFLUXDB_USER_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":2003,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":8083,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":8086,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":8090,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":25826,"protocol":"UDP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/var/lib/influxdb"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"chaos-armstronghab-influxdb"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
    manager: Go-http-client
    operation: Update
    time: "2020-06-28T23:16:09Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-06-28T23:17:41Z"
  name: influxdb
  selfLink: /apis/apps/v1/namespaces/armstronghab/deployments/influxdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-armstronghab-influxdb
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-06-28T20:01:32Z"
        field.cattle.io/ports: '[[{"containerPort":8083,"dnsName":"influxdb-hostport","hostPort":8083,"kind":"HostPort","name":"ui1","protocol":"TCP","sourcePort":8083},{"containerPort":8086,"dnsName":"influxdb-hostport","hostPort":8086,"kind":"HostPort","name":"ui2","protocol":"TCP","sourcePort":8086},{"containerPort":8090,"dnsName":"influxdb-hostport","hostPort":8090,"kind":"HostPort","name":"ui3","protocol":"TCP","sourcePort":8090},{"containerPort":25826,"dnsName":"influxdb-hostport","hostPort":25826,"kind":"HostPort","name":"comms1","protocol":"UDP","sourcePort":25826},{"containerPort":2003,"dnsName":"influxdb-hostport","hostPort":2003,"kind":"HostPort","name":"comms2","protocol":"TCP","sourcePort":2003}]]'
        field.cattle.io/publicEndpoints: '[{"addresses":["192.168.2.81"],"nodeId":"c-jxthh:m-12348520c6d2","port":8083,"protocol":"TCP"},{"addresses":["192.168.2.81"],"nodeId":"c-jxthh:m-12348520c6d2","port":8086,"protocol":"TCP"},{"addresses":["192.168.2.81"],"nodeId":"c-jxthh:m-12348520c6d2","port":8090,"protocol":"TCP"},{"addresses":["192.168.2.81"],"nodeId":"c-jxthh:m-12348520c6d2","port":25826,"protocol":"UDP"},{"addresses":["192.168.2.81"],"nodeId":"c-jxthh:m-12348520c6d2","port":2003,"protocol":"TCP"}]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-armstronghab-influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "123456789"
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_DATA_ENGINE
          value: tsm1
        - name: INFLUXDB_DB
          value: openhab_db
        - name: INFLUXDB_READ_USER
          value: openhab_ro
        - name: INFLUXDB_READ_USER_PASSWORD
          value: "123456789"
        - name: INFLUXDB_REPORTING_DISABLED
          value: "false"
        - name: INFLUXDB_USER
          value: openhab
        - name: INFLUXDB_USER_PASSWORD
          value: "123456789"
        image: influxdb:latest
        imagePullPolicy: Always
        name: influxdb
        ports:
        - containerPort: 8083
          hostPort: 8083
          name: ui1
          protocol: TCP
        - containerPort: 8086
          hostPort: 8086
          name: ui2
          protocol: TCP
        - containerPort: 8090
          hostPort: 8090
          name: ui3
          protocol: TCP
        - containerPort: 25826
          hostPort: 25826
          name: comms1
          protocol: UDP
        - containerPort: 2003
          hostPort: 2003
          name: comms2
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: chaos-armstronghab-influxdb
          subPath: ArmstrongHAB/influxdb
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: chaos-armstronghab-influxdb
        persistentVolumeClaim:
          claimName: chaos-armstronghab
status: {}
